import { StyleSheet, Dimensions, Platform } from 'react-native';
import { Colors } from '@/constants/theme';

const { width } = Dimensions.get('window');

export const createStyles = (colorScheme: 'light' | 'dark') => {
  const theme = Colors[colorScheme ?? 'light'];

  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.background,
    },

    saveButton: {
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 10,
      backgroundColor: 'rgba(255, 255, 255, 0.2)',
    },
    saveButtonText: {
      color: '#ffffff',
      fontWeight: '700',
      fontSize: 13,
    },
    dayContainer: {
      marginTop: 20,
      marginHorizontal: 16,
      backgroundColor: colorScheme === 'dark' ? 'rgba(255,255,255,0.03)' : 'rgba(0,0,0,0.02)',
      borderRadius: 24,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: theme.border,
    },
    dayHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: 20,
    },
    dayTitleContainer: {
      flexDirection: 'column',
    },
    dayTitle: {
      fontSize: 18,
      fontWeight: '800',
      color: theme.primary,
    },
    dayDate: {
      fontSize: 12,
      color: theme.tertiary,
      marginTop: 2,
    },
    dayContent: {
      paddingBottom: 48, // Increased to provide ample spacing below stay options and cards
      paddingHorizontal: 16,
    },
    sectionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginTop: 20,
      marginBottom: 12,
      paddingRight: 8,
      zIndex: 10,
    },
    sectionTitle: {
      fontSize: 14,
      fontWeight: '700',
      color: theme.tertiary,
      marginLeft: 4,
      textTransform: 'uppercase',
      letterSpacing: 1,
    },
    dropdownMenu: {
      position: 'absolute',
      top: 30,
      right: 0,
      backgroundColor: colorScheme === 'dark' ? '#1e293b' : '#ffffff',
      borderRadius: 12,
      padding: 8,
      minWidth: 160,
      zIndex: 100,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 10,
      elevation: 5,
      borderWidth: 1,
      borderColor: theme.border,
    },
    dropdownItem: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 12,
      borderRadius: 8,
    },
    dropdownText: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.primary,
      marginLeft: 10,
    },
    // Must Have Card
    mustHaveCard: {
      backgroundColor: colorScheme === 'dark' ? '#1a1d2e' : '#ffffff',
      borderRadius: 20,
      padding: 20,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: theme.border,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 2,
    },
    cardHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      marginBottom: 12,
    },
    timeTag: {
      backgroundColor: theme.accentTeal + '15',
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 8,
    },
    timeText: {
      fontSize: 12,
      fontWeight: '800',
      color: theme.accentTeal,
    },
    durationText: {
      fontSize: 12,
      fontWeight: '600',
      color: theme.tertiary,
    },
    cardTitle: {
      fontSize: 17,
      fontWeight: '800',
      color: theme.primary,
      marginBottom: 6,
    },
    cardSummary: {
      fontSize: 13,
      color: theme.tertiary,
      lineHeight: 18,
    },
    arrivalNote: {
      fontSize: 12,
      color: theme.accentOrange,
      fontFamily: 'Inter_600SemiBold',
      marginTop: 8,
      backgroundColor: theme.accentOrange + '10',
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 6,
      alignSelf: 'flex-start',
    },
    // Optional Activity Card
    optionalCard: {
      backgroundColor: colorScheme === 'dark' ? 'rgba(255,255,255,0.05)' : '#ffffff',
      borderRadius: 18,
      padding: 16,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: theme.border,
      flexDirection: 'row',
      alignItems: 'center',
    },
    optionalCardSelected: {
      borderColor: theme.accentTeal,
      backgroundColor: theme.accentTeal + '08',
    },
    optionalInfo: {
      flex: 1,
      marginRight: 12,
    },
    optionalTitle: {
      fontSize: 14,
      fontWeight: '700',
      color: theme.primary,
    },
    optionalDetails: {
      fontSize: 11,
      color: theme.tertiary,
      marginTop: 2,
    },
    activityActions: {
      flexDirection: 'column',
      alignItems: 'stretch',
      minWidth: 80,
    },
    addButton: {
      backgroundColor: '#2e8b58',
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 2,
    },
    addedButton: {
      backgroundColor: 'transparent',
      borderWidth: 1.5,
      borderColor: '#2e8b58',
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
    },
    addButtonText: {
      color: '#ffffff',
      fontSize: 13,
      fontWeight: '700',
    },
    addedButtonText: {
      color: '#2e8b58',
      fontSize: 13,
      fontWeight: '700',
    },
    skipButton: {
      marginTop: 8,
      paddingVertical: 6,
      alignItems: 'center',
    },
    skipButtonText: {
      color: theme.tertiary,
      fontSize: 12,
      fontWeight: '600',
      textDecorationLine: 'underline',
    },
    // Stay Options
    stayCard: {
      width: 220,
      backgroundColor: colorScheme === 'dark' ? 'rgba(255,255,255,0.04)' : '#ffffff',
      borderRadius: 20,
      marginRight: 12,
      padding: 14,
      borderWidth: 2,
      borderColor: theme.border,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.08,
      shadowRadius: 8,
      elevation: 3,
    },
    stayCardSelected: {
      borderColor: theme.accent,
      shadowOpacity: 0.18,
      shadowRadius: 12,
      elevation: 6,
    },
    stayTierBadge: {
      alignSelf: 'flex-start',
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 6,
      marginBottom: 10,
    },
    stayTierText: {
      color: '#fff',
      fontSize: 9,
      fontWeight: '800',
      letterSpacing: 0.8,
    },
    stayNameRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 4,
    },
    stayCheck: {
      width: 18,
      height: 18,
      borderRadius: 9,
      alignItems: 'center',
      justifyContent: 'center',
    },
    stayName: {
      flex: 1,
      fontSize: 13,
      fontWeight: '700',
      color: theme.primary,
      marginRight: 6,
    },
    stayPrice: {
      fontSize: 12,
      fontWeight: '800',
      marginBottom: 1,
    },
    stayPriceNote: {
      fontSize: 9,
      color: theme.tertiary,
      marginBottom: 6,
    },
    ratingContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 8,
    },
    ratingText: {
      fontSize: 10,
      color: theme.tertiary,
      marginLeft: 3,
    },
    stayDescription: {
      fontSize: 10,
      color: theme.secondary,
      lineHeight: 14,
    },
    // legacy — kept for compat
    stayImage: { display: 'none' },
    stayInfo: { display: 'none' },
    // Cost Bar
    costBar: {
      position: 'absolute',
      bottom: 90,
      left: 20,
      right: 20,
      backgroundColor: '#010411', // Deep dark
      borderRadius: 24,
      padding: 20,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.4,
      shadowRadius: 20,
      elevation: 10,
    },
    costLabel: {
      color: 'rgba(255, 255, 255, 0.6)',
      fontSize: 12,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 1,
    },
    costValue: {
      color: '#ffffff',
      fontSize: 24,
      fontWeight: '900',
      marginTop: 2,
    },
    // Standout Cost Breakdown Card at the top of the plan list
    costBreakdownCard: {
      backgroundColor: colorScheme === 'dark' ? '#090d16' : '#0f172a',
      borderRadius: 24,
      padding: 20,
      marginHorizontal: 16,
      marginTop: 16,
      marginBottom: 16,
      borderWidth: 1.5,
      borderColor: colorScheme === 'dark' ? 'rgba(255, 255, 255, 0.1)' : 'rgba(255, 255, 255, 0.05)',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.15,
      shadowRadius: 12,
      elevation: 4,
    },
    breakdownHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 16,
      borderBottomWidth: 1,
      borderBottomColor: 'rgba(255, 255, 255, 0.1)',
      paddingBottom: 16,
    },
    breakdownTitle: {
      color: 'rgba(255, 255, 255, 0.6)',
      fontSize: 12,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 1,
    },
    breakdownRange: {
      color: '#ffffff',
      fontSize: 18,
      fontWeight: '900',
      fontFamily: Platform.OS === 'ios' ? 'Outfit-Bold' : 'Outfit_700Bold',
    },
    breakdownGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      gap: 12,
    },
    breakdownItem: {
      width: '47%',
      backgroundColor: 'rgba(255, 255, 255, 0.05)',
      borderRadius: 16,
      padding: 12,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    breakdownIconContainer: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: 'rgba(255, 255, 255, 0.1)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    breakdownTextContainer: {
      flex: 1,
    },
    breakdownLabel: {
      color: 'rgba(255, 255, 255, 0.5)',
      fontSize: 10,
      fontWeight: '600',
      textTransform: 'uppercase',
    },
    breakdownValue: {
      color: '#ffffff',
      fontSize: 13,
      fontWeight: '800',
      marginTop: 2,
    },
  });
};
